version: '3'

services:

  email_ms:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/ms_email
    env_file:
      - .env
      - .env.test
    external_links:
      - host.docker.internal

  user_ms:
    image: ghcr.io/samuel-ricardo/ems_user:main
    ports:
      - "8081:8080"
    env_file:
      - .env.user
    external_links:
      - host.docker.internal

  user_postgres:
    image: postgres
    restart: always
    env_file:
      - .env.user
    volumes:
      - .docker/user/postgres:/data/postgres
    ports:
      - "5432:5432"