version: '3'

services:

  email_ms:
    build: .
    depends_on:
      - email_postgres
      - rabbitmq
    ports:
      - "8081:8081"
    volumes:
      - .:/ms_email
    env_file:
      - .env
      - .env.test
    external_links:
      - host.docker.internal

  user_ms:
    image: ghcr.io/samuel-ricardo/ems_user:main
    depends_on:
      - user_postgres
      - rabbitmq
    ports:
      - "8080:8080"
    env_file:
      - .env.user
    external_links:
      - host.docker.internal

  email_postgres:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - .docker/email/postgres:/data/postgres
    ports:
      - "5432:5432"
    external_links:
      - host.docker.internal

  user_postgres:
    image: postgres
    restart: always
    env_file:
      - .env.user
    volumes:
      - .docker/user/postgres:/data/postgres
    ports:
      - "5431:5432"
    external_links:
      - host.docker.internal

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - user_postgres
    env_file:
      - .env
    volumes:
      - .docker/pgadmin:/database/admin/pgadmin
    ports:
      - "5050:80"
    external_links:
      - host.docker.internal

  rabbitmq:
    image: rabbitmq:management
    env_file:
      - .env
      - .env.test
    ports:
      - "5672:5672"
      - "15672:15672"
    external_links:
      - host.docker.internal

networks:
  default:
    driver: bridge