broker:
  queue:
    email:
      name: default.email

server:
  port: 8081

spring:

  mail:
    username: ${OFFICIAL_EMAIL_ACCOUNT_USER:account@mail.com}
    password: ${OFFICIAL_EMAIL_ACCOUNT_PASS:123}

  datasource:
    url: ${DATABASE_URL:jdbc:h2:mem:ms_user}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASS:admin}
    driver-class-name: ${POSTGRES_DRIVER:org.h2.Driver}

  jpa:
    database-platform: ${POSTGRES_DIALECT:org.hibernate.dialect.H2Dialect}
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
